name: terraform-worfklow

on:
  push:
    branches:
    - main
    - staging
    - develop
    paths:
    - '**'

jobs:
  init:
    name: Initialization
    runs-on: ubuntu-latest
    outputs:
      sha7: ${{ steps.param.outputs.sha7 }}
      threads: ${{ steps.param.outputs.threads }}
      last_step: ${{ steps.param.outputs.last_step }}
      dev_directories: ${{ steps.param.outputs.dev_directories }}
      test_directories: ${{ steps.param.outputs.test_directories }}
      prod_directories: ${{ steps.param.outputs.prod_directories }}
    steps:
      - name: Define settings
        id: param
        env:
          GITHUB_REF: ${{ github.ref }} 
          GITHUB_SHA: ${{ github.sha }}
          DEV_DIRECTORIES: ${{ secrets.TF_DEV_DIRECTORIES }}
          TEST_DIRECTORIES: ${{ secrets.TF_TEST_DIRECTORIES }}
          PROD_DIRECTORIES: ${{ secrets.TF_PROD_DIRECTORIES }}
        run: |
          GITHUB_SHORTSHA=${GITHUB_SHA:0:7}
          GITHUB_BRANCH=${GITHUB_REF##*/}
          echo GITHUB_SHA=$GITHUB_SHA
          echo GITHUB_SHORTSHA=$GITHUB_SHORTSHA
          echo GITHUB_REF=$GITHUB_REF
          echo GITHUB_BRANCH=$GITHUB_BRANCH

          if [ "$GITHUB_BRANCH" == "main" ]
          then
              echo "::set-output name=last_step::3"
          elif [ "$GITHUB_BRANCH" == "staging" ]
          then
              echo "::set-output name=last_step::2"
          elif [ "$GITHUB_BRANCH" == "develop" ]
          then
              echo "::set-output name=last_step::1"
          else
              echo "[-] Error unaccepted branch name"
              exit 1
          fi
          echo "::set-output name=sha7::$GITHUB_SHORTSHA"
          echo "::set-output name=threads::4"

          # Development working directories
          if [ "$DEV_DIRECTORIES" != "" ]
          then
              DEV_DIRECTORIES=$(echo "$DEV_DIRECTORIES" | cut -c2)
              echo "::set-output name=dev_directories::$DEV_DIRECTORIES"
          else
              echo "::set-output name=dev_directories::[\".\"]"
          fi

          # Testing working directories
          if [ "$TEST_DIRECTORIES" != "" ]
          then
              TEST_DIRECTORIES=$(echo "$TEST_DIRECTORIES" | cut -c2)
              echo "::set-output name=test_directories::$TEST_DIRECTORIES"
          else
              echo "::set-output name=test_directories::[\".\"]"
          fi

          # Production working directories
          if [ "$PROD_DIRECTORIES" != "" ]
          then
              PROD_DIRECTORIES=$(echo "$PROD_DIRECTORIES" | cut -c2)
              echo "::set-output name=prod_directories::$PROD_DIRECTORIES"
          else
              echo "::set-output name=prod_directories::[\".\"]"
          fi
      - name: Show output values
        id: print
        run: |
          echo "sha7=${{ steps.param.outputs.sha7 }}"
          echo "threads=${{ steps.param.outputs.threads }}"
          echo "last_step=${{ steps.param.outputs.last_step }}"
          echo "dev_directories=${{ steps.param.outputs.dev_directories }}"
          echo "test_directories=${{ steps.param.outputs.test_directories }}"
          echo "prod_directories=${{ steps.param.outputs.prod_directories }}"

  dev-fmt:
    name: Format codes
    needs: [init]
    runs-on: ubuntu-latest
    if: needs.init.outputs.last_step >= '1'
    environment: development
    strategy:
      max-parallel: 1
      matrix:
        content: ${{ fromJson(needs.init.outputs.dev_directories) }}
    steps:
      - name: Simple echo
        id: echo
        run: |
          echo 40

  dev-pull-request:
    name: Commit changes
    needs: [dev-fmt]
    runs-on: ubuntu-latest
    if: needs.init.outputs.last_step >= '1'
    steps:
      - name: Simple echo
        id: echo
        run: |
          echo 41

  test-deploy:
    name: Deploy on staging environment
    needs: [init, dev-pull-request]
    runs-on: ubuntu-latest
    if: needs.init.outputs.last_step >= '2'
    environment: testing
    strategy:
      max-parallel: 1
      matrix:
        content: ${{ fromJson(needs.init.outputs.test_directories) }}
    steps:
      - name: Simple echo
        id: echo
        run: |
          echo 42

  prod-deploy:
    name: Deploy on production
    needs: [init, test-deploy]
    runs-on: ubuntu-latest
    if: needs.init.outputs.last_step >= '3'
    environment: production
    strategy:
      max-parallel: 1
      matrix:
        content: ${{ fromJson(needs.init.outputs.prod_directories) }}
    steps:
      - name: Simple echo
        id: echo
        run: |
          echo 43
