name: terraform-worfklow

on:
  push:
    branches:
    - main
    - staging
    - develop
    paths:
    - '**'

jobs:
  init:
    name: Initialization
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.param.outputs.environment }}
      sha7: ${{ steps.param.outputs.sha7 }}
      threads: ${{ steps.param.outputs.threads }}
    steps:
      - name: Define environment
        id: param
        env:
          GITHUB_REF: ${{ github.ref }} 
          GITHUB_SHA: ${{ github.sha }}
        run: |
          GITHUB_SHORTSHA=${GITHUB_SHA:0:7}
          GITHUB_BRANCH=${GITHUB_REF##*/}
          echo GITHUB_SHA=$GITHUB_SHA
          echo GITHUB_SHORTSHA=$GITHUB_SHORTSHA
          echo GITHUB_REF=$GITHUB_REF
          echo GITHUB_BRANCH=$GITHUB_BRANCH

          if [ "$GITHUB_BRANCH" == "main" ]
          then
            echo "::set-output name=environment::production"
          elif [ "$GITHUB_BRANCH" == "staging" ]
          then
            echo "::set-output name=environment::testing"
          elif [ "$GITHUB_BRANCH" == "develop" ]
          then
            echo "::set-output name=environment::development"
          else
            echo "[-] Error unaccepted branch name"
            exit 1
          fi
          echo "::set-output name=sha7::$GITHUB_SHORTSHA"
          echo "::set-output name=threads::8"
      - name: Show output values
        id: print
        run: |
          echo "environment=${{ steps.param.outputs.environment }}"
          echo "sha7=${{ steps.param.outputs.sha7 }}"
          echo "threads=${{ steps.param.outputs.threads }}"

  env-job:
    name: Environment job
    needs: [init]
    runs-on: ubuntu-latest
    environment: ${{ fromJson(needs.init.output.environment) }}
    steps:
      - name: Simple echo
        id: echo
        run: |
          echo 42
